version: 2
project_name: refactorkit
before:
  hooks:
builds:
  - main: .
    binary: refactorkit
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/prokizzle/refactorkit/internal/version.Version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: >-
      refactorkit-
      {{- if eq .Os "darwin" }}mac-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "#86" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "0.0.0-{{ .Timestamp }}"
aurs:
  - name: refactorkit
    homepage: "https://github.com/prokizzle/refactorkit"
    description: "terminal based AI assistant for software refactoring and development"
    maintainers:
      - "prokizzle"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/refactorkit-bin.git"
    provides:
      - refactorkit
    conflicts:
      - refactorkit
    package: |-
      install -Dm755 ./refactorkit "${pkgdir}/usr/bin/refactorkit"
brews:
  - repository:
      owner: prokizzle
      name: homebrew-tap
    name: refactorkit
    description: "Transform vibe-coded apps into production-grade software"
    homepage: "https://refactorkit.dev"
    install: |
      bin.install "refactorkit"
nfpms:
  - maintainer: kujtimiihoxha
    description: terminal based agent that can build anything
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^ci:"
      - "^ignore:"
      - "^example:"
      - "^wip:"
